version: '3.8'

services:
  web:
    build:
      context: ./prod_dockerfile
      dockerfile:  Dockerfile.prod
    command:   gunicorn -w 4 api:app
    expose:
      - 8000
    ports:
      - "8000:8000"
  nginx:
    build: ./robot_framework/nginx
    ports:
    - "1337:80"
    depends_on:
    - web
