version: '3.8'

services:
  web:
    build:
      context: ./robot_framework/web
      dockerfile: Dockerfile.robot_test
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
  nginx:
    build: ./robot_framework/nginx
    ports:
      - "1337:80"
    depends_on:
      - web