name: PA_TDL

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8' # Remplacez x par le numéro de la version de Python que vous utilisez
      - name: Install dependencies
        run: pip install -r  ./../../prod_dockerfile/web/requirements.txt
      - name: Run tests
        run: pytest
          
